# Generated by Django 3.1.2 on 2020-11-25 22:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('custport', '0003_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='iteminstance',
            name='cart',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='custport.cart'),
        ),
    ]
