# Generated by Django 3.1.3 on 2020-11-26 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custport', '0005_auto_20201125_1703'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='picture',
            field=models.ImageField(default='images/default.png', upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='iteminstance',
            name='status',
            field=models.CharField(blank=True, choices=[('a', 'Available'), ('c', 'Cart'), ('o', 'Order')], default='a', help_text='Item availability', max_length=1),
        ),
    ]
