# Generated by Django 3.1.2 on 2020-11-30 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custport', '0006_auto_20201125_2220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iteminstance',
            name='status',
            field=models.CharField(blank=True, default='a', help_text='Item availability', max_length=1),
        ),
    ]
