# Generated by Django 3.1.2 on 2020-12-01 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custport', '0007_auto_20201130_1338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iteminstance',
            name='status',
            field=models.CharField(blank=True, help_text='Item availability', max_length=1),
        ),
    ]
